import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";
import "../style/reset.css";
import "../style/utility.css";
import "../style/variable.css";
const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="layout">
          <Navbar />
          <main className="main">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
